#!/bin/bash

GP=$1

REQUIRED_FILE="./ftc"

echo "" >> detailed_results_$GP
echo "Résultats pour regex" >> detailed_results_$GP

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found." >> recap_result_$GP
    exit 1
fi

function test_find_regex_exact () {
    if [ ! "$(./ftc $1 "-name" $2)" == "$(find "$1" "-regex" "$2" "-type" "f")" ];
    then
        echo "🔴 Test of regex failed for \"$2\"" >> detailed_results_$GP
        echo "🔴 Test non validé pour regex" >> recap_result_$GP
    else
        echo "✅ Test of find with regex succeeded (regex: \"$2\")." >> detailed_results_$GP
    fi
}

test_find_regex_exact "arbre/" ".*aw.gif" "arbre/different/especially/law.gif"

function test_find_regex () {
    if [ ! "$(./ftc $1 "-name" $2 | wc -l)" == "$(find "$1" "-regex" "$2" "-type" "f" | wc -l)" ];
    then
        echo "🔴 Test of regex failed for \"$2\"" >> detailed_results_$GP
        echo "🔴 Test non validé pour regex" >> recap_result_$GP
    else
        echo "✅ Test of find with regex succeeded (regex: \"$2\")." >> detailed_results_$GP
    fi
}

test_find_regex "arbre/" ".*[^a-s]ly.txt" "1"
test_find_regex "arbre/" ".*[^a-t]ly.txt" "0"

echo "✅ Test validé pour regex" >> recap_result_$GP